package hello;

import com.aspectran.core.activity.Translet;
import com.aspectran.core.context.bean.annotation.Configuration;
import com.aspectran.core.context.bean.annotation.Request;
import com.aspectran.core.context.bean.annotation.Transform;
import com.aspectran.core.util.logging.Log;
import com.aspectran.core.util.logging.LogFactory;

@Configuration
public class SimplestAction {
	
	private final Log log = LogFactory.getLog(SimplestAction.class);

	@Request(translet="/ga-annotated-config/helloWorld", actionId="hello")
	@Transform(transformType="transform/text")
	public String helloWorld(Translet translet) {
		String msg = "Hello, World.";
		
		log.info("The message generated by my first aciton is: " + msg);

		return msg;
	}

}
