package sample;

import com.aspectran.core.activity.Translet;
import com.aspectran.core.component.bean.annotation.Action;
import com.aspectran.core.component.bean.annotation.Configuration;
import com.aspectran.core.component.bean.annotation.Dispatch;
import com.aspectran.core.component.bean.annotation.Request;
import com.aspectran.core.component.bean.annotation.Transform;
import com.aspectran.core.context.rule.type.MethodType;
import com.aspectran.core.context.rule.type.TransformType;
import com.aspectran.core.util.logging.Log;
import com.aspectran.core.util.logging.LogFactory;

import java.util.Map;

@Configuration
public class SampleAction {

    private final Log log = LogFactory.getLog(SampleAction.class);

    /**
     * http://localhost:8080/ga-annotated-config/helloWorld
     */
    @Request(translet = "helloWorld")
    @Transform(type = TransformType.XML)
    @Action(id = "message")
    public String helloWorld() {
        String msg = "Hello, World.";

        log.info("The message generated by my first action is: " + msg);

        return msg;
    }

    /**
     * http://localhost:8080/ga-annotated-config/front/helloWorld
     */
    @Request(translet = "front/${templateName}", method = MethodType.ALL)
    @Dispatch(name = "${templateName}")
    @Action(id = "title")
    public String restHelloWorld() {
        return "The message generated by my first action is: ";
    }

    /**
     * http://localhost:8080/ga-annotated-config/echo/this-is-a-message
     */
    @Request(translet = "echo/${echoMsg}", method = MethodType.ALL)
    @Transform(type = TransformType.JSON, pretty = true)
    @Action(id = "message")
    public String restEchoMessage(Translet translet) {
        String echoMsg = translet.getParameter("echoMsg");

        log.info("The message generated by my third action is: " + echoMsg);

        return echoMsg;
    }

    /**
     * http://localhost:8080/ga-annotated-config/echoParams?param1=1&param2=2
     */
    @Request(translet = "echoParams")
    @Transform(type = TransformType.JSON, pretty = true)
    @Action(id = "params")
    public Map<String, Object> echoParams(Translet translet) {
        Map<String, Object> params = translet.getAllParameters();

        log.info("params: " + params);

        return params;
    }

}
